In [9]:
import numpy as np

In [13]:
vect=np.array([2,3])
print(vect)

[2 3]


In [14]:
vect2=np.array([4,6])
print(vect2)

[4 6]


 جمع برای دو ماتریس : درایه های نظیر به نظیر رو جمع می کنیم ی

 نظیر به نظیر :
 1,2
 3,4

5,6
9,2

یک با 5 نظیر به نظیره
2با 6
و...

In [19]:
print(vect,vect2)
np.add(vect,vect2)

[2 3] [4 6]


array([6, 9])

برای تفریق دوتا ماتریس باید درایه های نظیر به نظیر از هم کم بشوند

In [21]:
print(vect,vect2)
np.subtract(vect,vect2)

[2 3] [4 6]


array([-2, -3])

 ضرب
 نظیر به نظیر ضرب میکنه

In [22]:
np.multiply(vect,vect2)

array([ 8, 18])

 ضرب یه عدد در بردار
 اون عدد رو در درایه ها ضرب میکنه

In [23]:
np.multiply(2,vect)

array([4, 6])

 ضرب داخلی دو بردار
 درایه های نظیر به نظیر رو ضرب میکنه آخرسر همه روباهم جمع میکنه

In [24]:
np.dot(vect,vect2)

26

 اندازه ی بردار

In [25]:
np.linalg.norm(vect)

3.605551275463989